services:
  mbudaniapp:
    build: .
    image: mbudani/mariana:v1
    container_name: mbudaniapp
    ports:
      - "${APP_PORT:-80}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production